_extends: .github
repository:
  name: semantic-release-workflow
  description: A reusable workflow for running semantic-release with recommended simplicity
  private: false
branches:
  - name: main
    protection: null
rulesets:
  - name: prevent destruction of the default branch
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: deletion
      - type: non_fast_forward
  - name: verification must pass
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          required_status_checks:
            - context: workflow-release
              integration_id: 15368
    bypass_actors:
      - actor_id: 3208999
        actor_type: Team
        bypass_mode: always
