name: Release

'on':
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: corepack enable npm
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm install -g corepack@latest
      - run: corepack npm clean-install
      - run: corepack npm audit signatures
      - name: semantic-release
        run: npx semantic-release@24.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}