name: Workflow Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

permissions:
  contents: read

jobs:
  workflow-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "lts/*"
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
